package org.Logica;

public enum TipoEvento {
    PARTICIPANTE_AGREGADO,
    PARTICIPANTE_ELIMINADO,
    TORNEO_INICIADO,
    ENFRENTAMIENTOS_GENERADOS,
    RESULTADOS_ACTUALIZADOS,
    TORNEO_FINALIZADO;
}